"""delete admin role

Revision ID: fc3fb08794b5
Revises: 7ac600c21b3a
Create Date: 2023-12-19 16:18:53.020114

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "fc3fb08794b5"
down_revision: Union[str, None] = "7ac600c21b3a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_is_admin", table_name="users")
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.BOOLEAN(), nullable=True))
    op.create_index("ix_users_is_admin", "users", ["is_admin"], unique=False)
    # ### end Alembic commands ###
