bot:
  token: 123456789:ABCDEFGHIJKLMOPRSTQYWZ

# Chat with posts from bot
chat_id: 123456789

# garbage chat, needed for delta-posting
temp_chat_id: 987654321

# Admin Telegram ID
superuser_id: 123456789

# Report customization
# With Jinja2 template you can access to ChanelDescription object via 'channel_listing' variable
#
#class ChannelDescription(BaseModel):
#    url: str
#    label: str
#    like_count: Optional[int] = None
#    concurrent_view_count: Optional[int] = None
#    duration: Optional[str] = None
#
report:
  template: | 
      <h1>✅ СЕЙЧАС В ЭФИРЕ:</h1>
      <br/>
      <ol type='1'>
      {% for channel in channels %}
          <li>
              <b><a href='{{channel.url}}'>{{channel.label}}</a></b> <br/>
              {% if channel.concurrent_view_count is not none %}
                  <b>👀{{channel.concurrent_view_count}}</b>
              {% endif %}
              {% if channel.like_count is not none %}
                  <b>👍{{channel.like_count}}</b>
              {% endif %}
              {% if channel.duration is not none %}
                  <b>🕑{{channel.duration}}</b>
              {% endif %}
          </li>
          <br/>
      {% endfor %}
      </ol>
      <hr/>
      <i>💬 Заходите в наш <a href='https://t.me/Discordovchat'>чат</a></i>

  empty: | 
    <b>🤷 Интересных стримов сейчас нет.</b>
    <hr/>
    <i>💬 Заходите в наш <a href='https://t.me/Discordovchat'>чат</a></i>

# start scheduler when start or do it after
start_scheduler: False
# interval between checks in seconds
interval_s: 60

# For notification from Twitch
# You can obtain from https://dev.twitch.tv/console
# twitch:
#   app_id: xxxxxxxxxxxxxxxxxxxxxxxxxx
#   app_secret: xxxxxxxxxxxxxxxxxxxxxxxxxx

# Path to cookie file for youtube-dlp
# youtube:
#  cookies_filepath: /path/to/cookies.txt
