# create deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-notifier
  namespace: yt-notifier-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-notifier
  template:
    metadata:
      labels:
        app: yt-notifier
    spec:
      containers:
      - name: yt-notifier
        image: bral1488/telegram-youtube-notifier:main
        imagePullPolicy: Always
        command: ["sh", "-c", "aerich upgrade && python -m src"]
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
          readOnly: true
        - name: config-volume
          mountPath: /app/cookies.txt
          subPath: cookies.txt
          readOnly: true
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 0
        env:
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: yt-notifier-config
                key: database.host
          - name: DATABASE_PORT
            valueFrom:
              configMapKeyRef:
                name: yt-notifier-config
                key: database.port
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: yt-notifier-secrets
                key: database.user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: yt-notifier-secrets
                key: database.password
          - name: DATABASE_NAME
            valueFrom:
              configMapKeyRef:
                name: yt-notifier-config
                key: database.name
      volumes:
      - name: config-volume
        configMap:
          name: yt-notifier-config
      tolerations:
      - key: "node.kubernetes.io/disk-pressure"
        operator: "Exists"
        effect: "NoSchedule"
